### ISSUE TITLE
`self._cluster.adapt(**self.adapt_kwargs)` is missing an `await`

### ISSUE THREAD

**Issue by parabolala** [PrefectHQ/prefect-dask#57]
When I specify `adapt_kwargs` argument to `DaskTaskRunner` (with a dask-gateway `GatewayCluster`), I'm seeing:

```
.../lib/python3.8/site-packages/prefect_dask/task_runners.py:298: RuntimeWarning: coroutine 'Gateway._adapt_cluster' was never awaited
  self._cluster.adapt(**self.adapt_kwargs)
```

pointing at these lines in `prefect-dask`:
```
            if self.adapt_kwargs:
                self._cluster.adapt(**self.adapt_kwargs)
```

Is the `_cluster.adapt()` line missing an `await` or is it an artifact of an interaction with dask-gateway clusters?

**Comment by madkinsz** [comment]
Hm; this might depend on the type of cluster implementation. We can use `inspect.iscoroutine` to see if the return value of `adapt` is a coro then await it if so.

**Comment by ahuang11** [comment]
I think this could be an issue upstream:
https://github.com/dask/dask-gateway/blob/main/dask-gateway/dask_gateway/client.py#L704-L728

**Comment by john-jam** [comment]
I hit that same warning when using the new [operator.KubeCluster](https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/operator/kubecluster/kubecluster.py#L48) on the `dask-kubernetes` repo instead of the soon-to-be-deprecated classic implementation:
```
/venvs/venv/lib/python3.8/site-packages/prefect_dask/task_runners.py:298: RuntimeWarning: coroutine 'KubeCluster._adapt' was never awaited
  self._cluster.adapt(**self.adapt_kwargs)
```

> Hm; this might depend on the type of cluster implementation. We can use inspect.iscoroutine to see if the return value of adapt is a coro then await it if so.
> I think this could be an issue upstream since [adapt](https://github.com/dask/dask-gateway/blob/main/dask-gateway/dask_gateway/client.py#L1101-L1116) is a synchronous function, but [_adapt_cluster](https://github.com/dask/dask-gateway/blob/main/dask-gateway/dask_gateway/client.py#L689-L702) is not, but sync should be called.

@madkinsz @ahuang11 I tried to solve that in [this other PR](https://github.com/PrefectHQ/prefect-dask/pull/41/files#diff-e48979d13e982d1ac163b900fac9a9d8cd8366b352dbc4b89b17d5b21de4120eR307-R309) that is now closed. But I think I did that poorly. I can try to fix it upstream but we have the same problem on 2 upstream repos. What do you suggest?
